---
- hosts: all
  sudo: true
  roles:
  - role: prometheus
    prometheus_global_labels:
      a: b
    prometheus_target_jobs:
    - job_name: 'web-server'
      scrape_interval: '5s'
      scrape_timeout: '10s'
      target_groups:
        targets:
          - "localhost:9090"
        labels:
          a: b

    - job_name: 'service_from_consul'
      scrape_interval: '5s'
      scrape_timeout: '10s'
      consul_sd_configs:
        - server: "localhost"
          datacenter: "dc1"
          scheme: "rpc"
          token: ""
          username: ""
          password: ""
          services:
            - myservicename
          tag_separator: ":"
