---
- hosts: all
  sudo: true
  roles:
  - role: prometheus
    prometheus_global_labels:
      a: b
    #prometheus_rule_files:
    #  - my.rules
    prometheus_sd_jobs:
      - job:
        name: 'api-server'
        scrape_interval: '5s'
        scrape_timeout: '10s'
        sd_name: 'dns.resovl.name.prod'
        sd_refresh_interval: '30s'
        metrics_path: '/metrics'
    prometheus_target_jobs:
      - job:
        name: 'web-server'
        scrape_interval: '5s'
        scrape_timeout: '10s'
        target_group:
        - target: "http://localhost:9090/metrics"
        labels:
          a: b

