---

- name: create prometheus group
  group:
    name={{ prometheus_group }}
    state=present
    system=yes

- name: create prometheus user
  user:
    name={{  prometheus_user }}
    group={{ prometheus_group }}
    system=yes
    createhome=no

- name: already installed check
  stat: path={{ prometheus_install_dir }}/prometheus
  register: binary_file

- name: install - checkout prometheus from github.com
  git:
    repo=https://github.com/prometheus/prometheus
    dest={{ prometheus_build_folder }}

- name: make prometheus
  command: make build
  args:
    chdir: "{{ prometheus_build_folder }}"
  when: not binary_file.stat.exists

- name: make directories
  file: 
    state=directory
    path={{ item }}
    owner={{ prometheus_user }}
    group={{ prometheus_group }}
    mode=0755
  with_items:
    - /etc/prometheus
    - /opt/prometheus
    - /var/log/prometheus

- name: move binary
  command: mv {{ prometheus_build_folder }}/prometheus {{ prometheus_install_dir }}/
  args:
    creates: /opt/prometheus/prometheus


