---

- name: install depencies
  include: depend.yml

- name: install prometheus
  include: install.yml

- name: configure prometheus
  include: config.yml

- name: setup service
  include: service.yml

