---
# tasks file for prometheus


- include: depend.yml

- include: install.yml

- include: config.yml

- name: install and start service
  runit: name={{ prometheus_service_name }} enabled=true state=up timeout=9 user={{ prometheus_user }} command='{{ prometheus_install_dir }}/prometheus -config.file=/etc/prometheus/prometheus.conf' 


#- name: consul - service
#  include: runit_service.yml
#  vars:
#    service_name: "{{ prometheus_service_name }}"
#    service_user: "{{ prometheus_user }}"
#    service_command: "{{ prometheus_install_dir }}/prometheus -config.file=/etc/prometheus/prometheus.conf "
#    service_env_vars:
#      GOMAXPROCS: "{{ansible_processor_cores + 1}}"

