---
# handlers file for prometheus

- name: restart prometheus
  runit:
    name={{ prometheus_service_name }} 
    action=restart
    state=up
    enabled=true
    timeout=9
  when: not prometheus_service_status.restarted

